# Site
name: 'IliCloudy'
description: 'IliCloudy is a tech blog for Cloud and IaC awesome people!'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
#disqus: 'ilicloudygit'
email: 'ili.tzima@gmail.com'
#mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    iliana:
      name:           Iliana
      site:           https://ilicloudy.github.io
      avatar:         /assets/images/avatar7.jpg
      bio:            "Blogger, techie into Cloud and IaC!"
      email:          ili_tzima@gmail.com
      twitter:        https://twitter.com/ili_tzima
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: iliana
      avatar: /assets/images/myphotoresized.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]